- hosts: ec2
  user: ec2-user

  vars:
    python_version: 2.7.9

  tasks:
  - name: install basic packages
    sudo: yes
    yum: name={{item}} state=present
    with_items:
    - git
    - vim
    - emacs

  - name: install pyenv and specified Python
    shell: |
      git clone https://github.com/yyuu/pyenv.git ~/.pyenv
      (
          echo 'export PYENV_ROOT=~/.pyenv'
          echo 'export PATH=$PYENV_ROOT/bin:$PATH'
          echo 'eval "$(pyenv init -)"'
      ) >> ~/.bashrc
      source ~/.bashrc
      pyenv install {{python_version}}
      pyenv rehash
      pyenv global {{python_version}}

  - name: install Python packages using pip
    pip: name={{item}}
    with_items:
    - tornado
